### ISSUE TITLE
DatabaseGPT for Postgres (and more?)

### ISSUE THREAD

**Issue by nicolaparo** [marcominerva/DatabaseGPT#14]
DatabaseGPT currently supports only scenarios where we have SqlServer databases. It doesn't currently support the case of a different SQL DBMS like Postgres, SQLite, MySql, etc... The major difference between all these DBMS is mainly the dialect of the SQL language used in the database and the required drivers themselves. 

Since a user who is interested in using DatabaseGPT to query a SqlServer might not be interested in having the drivers also for another DBMS, it is preferrable to not include all the possible database drivers in a single package.
I suggest then the refactor of the solution as follows:
- DatabaseGPT: this will be the package that contains all the logic independently from the DBMS. (The actual requests to the OpenAI endpoints should be handled here)
- DatabaseGPT.Core: this will contain the definition of the interfaces and the basic classes required by the database specific implementations. (For example, the definition of an interface IDatabaseProvider)
- DatabaseGPT.SqlServer: this will contain the SqlServer specific logic
- DatabaseGPT.Npgsql: this will contain the Postgres specific logic
- DatabaseGPT.MySql (future)
- DatabaseGPT.SQLite (future)

If the idea is valid and interesting, I can start to design a more detailed refactoring plan and the database-specific implementations for SqlServer and Postgres.

**Comment by marcominerva** [comment]
The idea is definitely interesting. I have some consideration about your suggestion:

- Use `Gpt` instead of `GPT` for the project name
- Instead of `DatabaseGpt.Core`, I would prefer `DatabaseGpt.Abstractions`, using the same naming convention that is adopted by Microsoft
- With this refactoring, the current `DatabaseGptConsole` project should be moved to a samples folder.

I have assigned the task to you @nicolaparo, thank your for collaboration!
